name = "sisipisiminecraft"
author = "totori775"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "718c68d52952b4ba6309b9d30a05d4e45f48fb8aa84d6f64b2a688521e45d69f"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
