
#[i] These are ONLY starting defaults for NEW worlds.
#[i] After a world is running, use their corresponding gamerules.
[gameplay]
	#Elixir of Vitality hearts limit (in HEARTS, not HP).
	#Range: 0 ~ 60
	elixirHeartsCap = 10
	#Whether piglins/brutes can spawn wearing special equipment.
	doPiglinEquipped = true

