#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
#Thu Mar 19 07:30:13 YEKT 2026
int.villages.spacing=45
int.villages.separation=20
boolean.villages.enabled_custom_config=true
int.villages.salt=10387312
